import Head from 'next/head';
import { Index } from '@/components/pages/Index';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* components/pagesで作成したIndexを表示する */}
      {/* TODO: 実装 */}
    </>
  );
}
